config/routes.rb
YoutubeItRailsAppExample::Application.routes.draw do
  resources :searches do
  new do
    post :show
    get  :save_search
  end
  end

  root :to => "searches#index"
end

app/models/search.rb
class Search < ActiveRecord::Base



  def self.get_last
      find(:all, :order => "id desc", :limit => 1).reverse
  end

  def self.search(search)
    find(:all, :conditions => ['"searches".text = '<< '"' << search.to_s << '"', "%#{search}%"])

  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :yt_client

  
  def yt_client
    @yt_client ||= YouTubeIt::Client.new(:username => YouTubeITConfig.username , :password => YouTubeITConfig.password , :dev_key => YouTubeITConfig.dev_key)
  end
  
end

app/controllers/searches_controller.rb
class SearchesController < InheritedResources::Base
  def show

    @yt_session ||= YouTubeIt::Client.new(:username => YouTubeITConfig.username , :password => YouTubeITConfig.password , :dev_key => YouTubeITConfig.dev_key)

    if params[:search].length < 1
      redirect_to searches_path
    else
    @sea = Search.search(params[:search])
    if @sea.length<1
      Search.create(:text => params[:search])
    end
    @sea = Search.search(params[:search])

    @sea.each do |search|
       @search = search.text
    end
    @v = @yt_session.videos_by(:query => @search, :per_page => 50)
    @a=Array.new()
    @b=Array.new()
    @c=Array.new()
    @d=Array.new()
    @urls=Array.new()
    @v.videos.each do |ccc|
      @a << ccc.view_count
      @b << ccc.rating
      @c << ccc.title
      @d << ccc.duration
      @urls << ccc.player_url
    end

    $i = 0
    $num = @b.length
    begin
      if @b[$i] && @a[$i] && (@a[$i]>20000) && @d[$i] && (@d[$i]<450)
        if @result
          if @result > (@a[$i]/(@b[$i].likes+0.5)+5000*(@b[$i].dislikes/(@b[$i].likes+0.5)))
            @result = (@a[$i]/(@b[$i].likes+0.5)+5000*(@b[$i].dislikes/(@b[$i].likes+0.5)))
            @final = @c[$i]
            @ur = @urls[$i]
          end
        else
          @result = (@a[$i]/(@b[$i].likes+0.5)+5000*(@b[$i].dislikes/(@b[$i].likes+0.5)))
          @final = @c[$i]
          @ur = @urls[$i]
        end
      end
      $i +=1
    end while $i < $num
  end
  end




def new

end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YouTube IT Demo</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">BELLA</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <li><a href="https://github.com/kylejginavan/youtube_it" target="_open">YouTube IT Sources</a></li>
          <li><a href="https://github.com/chebyte/youtube_it_rails_app_example" target="_open">Example Sources</a></li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf"></ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> YouTube IT .</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<h1>Listing searches</h1>

<table>
  <tr>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @searches.each do |search| %>
  <tr>
    <td><%= search.text %></td>
    <td><%= link_to 'Show', search %></td>
    <td><%= link_to 'Edit', edit_search_path(search) %></td>
    <td><%= link_to 'Destroy', search, :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<div class="content">
  <h2 class="Artist"><%= t("web-app-theme.new", :default => "New")%>  Search</h2>
  <div class="inner">
    <p>Insert query</p>

    <% form_tag @search, :method => 'post' do %>
        <p>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search" %>
        </p>
  <% end %>
  </div>
</div>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @final %>
</p>

  <%= link_to 'Watch NOW!', '' << @ur << '' %></p>


<%= link_to 'DONE', searches_path %></p>